# Generated by Django 4.1.7 on 2023-03-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0002_rename_question_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='full_name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tree',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tree',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tree',
            name='tree_name',
            field=models.CharField(max_length=50),
        ),
    ]
