# Generated by Django 4.1.7 on 2023-03-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0005_tree_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
