# Generated by Django 4.1.7 on 2023-03-04 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0008_alter_tree_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ['parent_id', 'name']},
        ),
        migrations.RemoveField(
            model_name='tree',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='offset',
        ),
    ]
