# Generated by Django 4.1.7 on 2023-03-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0009_alter_tree_options_remove_tree_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='tree_name',
        ),
    ]
