# Generated by Django 4.1.7 on 2023-03-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0010_remove_tree_tree_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='up_elem',
        ),
    ]
