# Generated by Django 4.1.7 on 2023-03-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0011_remove_tree_up_elem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='full_name',
            new_name='link',
        ),
    ]
