# Generated by Django 4.1.7 on 2023-03-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0012_rename_full_name_tree_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='link',
            field=models.CharField(max_length=2048),
        ),
    ]
