# Generated by Django 4.1.7 on 2023-03-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0013_alter_tree_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ['-menu', 'parent_id', 'name']},
        ),
        migrations.AddField(
            model_name='tree',
            name='link_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
