# Generated by Django 4.1.7 on 2023-03-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0014_alter_tree_options_tree_link_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='link_name',
            new_name='named_url',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='link',
            new_name='url',
        ),
    ]
