# Generated by Django 4.1.7 on 2023-03-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0016_alter_tree_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'ordering': ['menu', 'parent_id', 'name']},
        ),
        migrations.AlterField(
            model_name='tree',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
