# Generated by Django 4.1.7 on 2023-03-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtree', '0017_alter_tree_options_alter_tree_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
